# Enhanced Synthetic Data Generation Configuration
# Includes industrial companies and expanded organizational diversity

generation:
  organizations:
    count: 15
    size_distribution:
      - type: startup
        range: [50, 200]
        weight: 0.2
      - type: scaleup
        range: [200, 1000]
        weight: 0.25
      - type: enterprise
        range: [1000, 10000]
        weight: 0.35
      - type: large_enterprise
        range: [10000, 100000]
        weight: 0.15
      - type: mega_corporation
        range: [100000, 500000]
        weight: 0.05

    # Expanded industries to include more industrial sectors
    industries:
      - technology
      - healthcare
      - finance
      - retail
      - manufacturing
      - automotive
      - aerospace
      - energy
      - oil_gas
      - chemicals
      - pharmaceuticals
      - construction
      - mining
      - utilities
      - transportation
      - logistics
      - consulting
      - nonprofit
      - education
      - telecommunications

    # Global regions with more coverage
    regions:
      - Silicon Valley, USA
      - New York, USA
      - Chicago, USA
      - Houston, USA
      - Los Angeles, USA
      - Toronto, Canada
      - London, UK
      - Berlin, Germany
      - Munich, Germany
      - Frankfurt, Germany
      - Paris, France
      - Milan, Italy
      - Madrid, Spain
      - Amsterdam, Netherlands
      - Zurich, Switzerland
      - Stockholm, Sweden
      - Copenhagen, Denmark
      - Singapore
      - Tokyo, Japan
      - Osaka, Japan
      - Seoul, South Korea
      - Shanghai, China
      - Beijing, China
      - Shenzhen, China
      - Mumbai, India
      - Bangalore, India
      - Delhi, India
      - Sydney, Australia
      - Melbourne, Australia
      - São Paulo, Brazil
      - Mexico City, Mexico
      - Buenos Aires, Argentina
      - Dubai, UAE
      - Riyadh, Saudi Arabia
      - Tel Aviv, Israel
      - Istanbul, Turkey
      - Cape Town, South Africa
      - Lagos, Nigeria

    maturity_stages:
      - seed
      - startup
      - growth
      - scaling
      - mature
      - established
      - transforming
      - declining
      - restructuring

  people:
    per_organization:
      min: 15
      max: 50

    hierarchy_levels:
      - level: 1
        titles: [CEO, President, Founder, Chairman]
        count: 1
      - level: 2
        titles: [VP, EVP, CTO, CFO, COO, CMO, CHRO, Chief Strategy Officer]
        count_range: [4, 8]
      - level: 3
        titles: [Director, Head of, General Manager, Country Manager]
        count_range: [6, 12]
      - level: 4
        titles: [Manager, Lead, Senior Manager, Principal, Senior]
        count_range: [8, 18]
      - level: 5
        titles: [Specialist, Coordinator, Analyst, Associate, Junior]
        count_range: [10, 25]

    # Expanded personality traits for more diversity
    personality_traits:
      - analytical
      - creative
      - decisive
      - collaborative
      - visionary
      - detail-oriented
      - pragmatic
      - innovative
      - empathetic
      - results-driven
      - strategic
      - diplomatic
      - assertive
      - adaptable
      - methodical
      - entrepreneurial
      - relationship-focused
      - data-driven
      - risk-tolerant
      - process-oriented

    communication_styles:
      - direct
      - diplomatic
      - collaborative
      - analytical
      - inspirational
      - assertive
      - consultative
      - influential
      - supportive
      - challenging

    decision_styles:
      - decisive
      - consultative
      - consensus-seeking
      - data-driven
      - intuitive
      - systematic
      - opportunistic
      - conservative
      - innovative
      - strategic

  scenarios:
    per_organization: 12

    # Expanded scenario types for industrial companies
    types:
      - strategic_planning
      - crisis_management
      - resource_allocation
      - market_expansion
      - digital_transformation
      - team_restructuring
      - product_launch
      - competitive_response
      - cost_optimization
      - innovation_initiative
      - merger_acquisition
      - regulatory_compliance
      - sustainability_initiative
      - supply_chain_optimization
      - technology_adoption
      - talent_acquisition
      - operational_excellence
      - customer_experience
      - risk_management
      - international_expansion

    urgency_levels:
      - low
      - medium
      - high
      - critical
      - emergency

    scopes:
      - department
      - cross-functional
      - business_unit
      - regional
      - company-wide
      - industry-wide
      - global
      - external

    delegation_chains:
      min_length: 3
      max_length: 8

      response_types:
        - accept
        - clarify
        - push_back
        - delegate_further
        - suggest_alternative
        - escalate
        - collaborate
        - defer

      response_distribution:
        accept: 0.25
        clarify: 0.30
        push_back: 0.12
        delegate_further: 0.15
        suggest_alternative: 0.08
        escalate: 0.05
        collaborate: 0.03
        defer: 0.02

# Enhanced diversity parameters
diversity:
  gender_balance: 0.5  # Target 50/50
  age_distribution:
    22-30: 0.15
    30-40: 0.35
    40-50: 0.30
    50-60: 0.15
    60-70: 0.05

  cultural_backgrounds:
    - North American
    - European
    - East Asian
    - South Asian
    - Southeast Asian
    - Latin American
    - Middle Eastern
    - African
    - Oceanic
    - Nordic
    - Eastern European
    - Central Asian

# Industrial company integration
industrial_integration:
  use_industrial_data: true
  industrial_data_path: "industrial_data/industrial_companies.json"
  integration_weight: 0.4  # 40% of organizations will be based on real industrial companies

# Enhanced output configuration
output:
  format: json
  pretty_print: true
  include_metadata: true
  batch_size: 15

  generate_analytics: true
  include_performance_metrics: true
  include_network_analysis: true

  file_naming:
    organizations: "org_{id}_{name}_{region}.json"
    people: "people_{org_id}_{region}.json"
    scenarios: "scenario_{org_id}_{type}_{urgency}_{id}.json"
    delegation_chains: "delegation_{org_id}_{scenario_id}_{length}.json"
    analytics: "analytics_{timestamp}.json"

# New sections for enhanced data generation
market_data:
  include_market_analysis: true
  include_competitor_analysis: true
  include_industry_trends: true

performance_metrics:
  financial_metrics: true
  operational_metrics: true
  innovation_metrics: true
  sustainability_metrics: true

technology_adoption:
  include_tech_stack: true
  digital_maturity_scoring: true
  automation_levels: true

supply_chain:
  include_supplier_networks: true
  global_operations: true
  logistics_complexity: true