services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: openai-voice-server
    ports:
      - "8787:8787"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: sh -c "npm ci && npm run server"
    volumes:
      - .:/app
      - server_node_modules:/app/node_modules
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: openai-voice-web
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0"
    volumes:
      - .:/app
      - web_node_modules:/app/node_modules
    depends_on:
      - server
    restart: unless-stopped

volumes:
  server_node_modules:
  web_node_modules:
