services:
  weaviate:
    image: semitechnologies/weaviate:1.25.0
    ports:
      - 8080:8080
      - 50051:50051
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai'
      OPENAI_APIKEY: '${OPENAI_API_KEY}'
      CLUSTER_HOSTNAME: 'node1'
    networks:
      - weaviate-demo

  demo-api:
    build: .
    ports:
      - 3333:8000
    environment:
      - WEAVIATE_URL=http://weaviate:8080
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - weaviate
    networks:
      - weaviate-demo

networks:
  weaviate-demo:
    driver: bridge